# Generated by Django 4.1.4 on 2023-01-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationFormation',
            fields=[
                ('description', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AvantageFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='BrancheFormation',
            fields=[
                ('description', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('code_echeance', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('duree', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('code_formation', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('intitule_formation', models.CharField(max_length=500)),
                ('duree_formation_mois', models.PositiveIntegerField()),
                ('duree_formation_heures', models.PositiveIntegerField()),
                ('duree_stage_semaines', models.PositiveIntegerField()),
                ('lien_cpf', models.URLField(blank=True, null=True)),
                ('tarif_sans_acompte', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acompte', models.DecimalField(decimal_places=2, max_digits=7)),
                ('lien_brochure', models.URLField()),
                ('attestation_formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.attestationformation')),
                ('branche_formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.brancheformation')),
                ('echeances_tarif_minus15', models.ManyToManyField(related_name='formations_minus15', to='formations.echeance')),
                ('echeances_tarif_minus25', models.ManyToManyField(related_name='formations_minus25', to='formations.echeance')),
                ('echeances_tarif_plain', models.ManyToManyField(related_name='formations_plain', to='formations.echeance')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('description', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QualiteRequisFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualites_requis', to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis_techniques', to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis_scolaires', to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganismeEmploiFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organismes_emploi', to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='MissionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='formations.formation')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='type_formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.typeformation'),
        ),
        migrations.CreateModel(
            name='EvolutionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='formations.formation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='echeance',
            constraint=models.CheckConstraint(check=models.Q(('duree__gt', 0)), name='duree_gt_0'),
        ),
        migrations.AddField(
            model_name='avantageformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avantages', to='formations.formation'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.CheckConstraint(check=models.Q(('duree_formation_mois__gt', 0), ('duree_formation_heures__gt', 0)), name='duree_formation_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.CheckConstraint(check=models.Q(('tarif_sans_acompte__gt', 0), ('acompte__gt', 0)), name='prix_gt_0'),
        ),
    ]
