# Generated by Django 4.1.4 on 2022-12-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrancheFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initule_formation', models.CharField(max_length=60, unique=True)),
                ('duree_formation_mois', models.PositiveIntegerField()),
                ('duree_formation_heures', models.PositiveIntegerField()),
                ('duree_stage', models.PositiveIntegerField()),
                ('lien_cpf', models.URLField(null=True)),
                ('tarif_sans_acompte', models.DecimalField(decimal_places=2, max_digits=7)),
                ('acompte', models.DecimalField(decimal_places=2, max_digits=7)),
                ('lien_brochure', models.URLField()),
                ('attestation_formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.attestationformation')),
                ('branche_formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.brancheformation')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualiteRequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganismeEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='type_formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.typeformation'),
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='DureeEcheance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.PositiveIntegerField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Avantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.CheckConstraint(check=models.Q(('duree_formation_mois__gt', 0), ('duree_formation_heures__gt', 0)), name='duree_formation_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.CheckConstraint(check=models.Q(('tarif_sans_acompte__gt', 0), ('acompte__gt', 0)), name='prix_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='dureeecheance',
            constraint=models.CheckConstraint(check=models.Q(('duree__gt', 0)), name='duree_gt_0'),
        ),
    ]
